-- Les 60 villes de Port Royale 3, extraites de son `ini/constdata.dat`
-- par `outils/extraire_pr3_monde.py`. NE PAS EDITER A LA MAIN.
--
-- `case` est la position sur la carte du monde de PR3, en cases de son
-- `ini/map.bmp` -- la meme unite que `sim/carte_monde.lua`.
-- `taille` vaut 1 (bourg), 2 (ville) ou 3 (grande ville) : 48, 8 et 4
-- villes respectivement. `produits` sont les CINQ marchandises que le
-- jeu fait produire a la ville : quatre du fonds commun, plus une
-- culture coloniale (teintures, cafe, cacao ou tabac) dictee par le climat.
--
-- La nation est celle du DEPART de PR3, sauf le Portugal, qui n'existe pas
-- chez lui et prend ici la cote ouest. Elle est d'epoque : Port Royale
-- et Curacao sont espagnoles, la Jamaique ne devenant anglaise qu'en 1655
-- et Curacao hollandaise qu'en 1634.

return {
  { cle = "corpus_christi", nom = "Corpus Christi", nation = "portugal", case = { 119, 175 }, taille = 1, region = 0,
    produits = { "bois", "ble", "metal", "vetements", "teinture" } },
  { cle = "nouvelle_orleans", nom = "Nouvelle Orléans", nation = "france", case = { 297, 140 }, taille = 3, region = 0,
    produits = { "sucre", "tissu", "briques", "pain", "teinture" } },
  { cle = "biloxi", nom = "Biloxi", nation = "france", case = { 346, 129 }, taille = 1, region = 0,
    produits = { "bois", "mais", "metal", "pain", "teinture" } },
  { cle = "pensacola", nom = "Pensacola", nation = "france", case = { 383, 133 }, taille = 1, region = 0,
    produits = { "coton", "tissu", "metal", "pain", "teinture" } },
  { cle = "port_saint_joe", nom = "Port Saint Joe", nation = "france", case = { 421, 151 }, taille = 1, region = 0,
    produits = { "sucre", "tissu", "metal", "pain", "teinture" } },
  { cle = "tampa", nom = "Tampa", nation = "france", case = { 487, 213 }, taille = 1, region = 0,
    produits = { "bois", "ble", "metal", "vetements", "teinture" } },
  { cle = "keys_de_floride", nom = "Keys de Floride", nation = "france", case = { 538, 312 }, taille = 1, region = 0,
    produits = { "fruits", "mais", "briques", "outils", "teinture" } },
  { cle = "tampico", nom = "Tampico", nation = "portugal", case = { 63, 362 }, taille = 1, region = 1,
    produits = { "bois", "ble", "sucre", "vetements", "cafe" } },
  { cle = "vera_cruz", nom = "Vera Cruz", nation = "portugal", case = { 87, 465 }, taille = 3, region = 1,
    produits = { "coton", "mais", "briques", "outils", "cafe" } },
  { cle = "villahermosa", nom = "Villahermosa", nation = "portugal", case = { 171, 519 }, taille = 1, region = 1,
    produits = { "sucre", "ble", "chanvre", "viande", "cafe" } },
  { cle = "campeche", nom = "Campêche", nation = "portugal", case = { 261, 454 }, taille = 1, region = 1,
    produits = { "bois", "mais", "briques", "viande", "cafe" } },
  { cle = "sisal", nom = "Sisal", nation = "portugal", case = { 283, 421 }, taille = 1, region = 1,
    produits = { "coton", "ble", "metal", "viande", "cafe" } },
  { cle = "cancun", nom = "Cancún", nation = "portugal", case = { 360, 433 }, taille = 1, region = 1,
    produits = { "sucre", "mais", "metal", "viande", "cafe" } },
  { cle = "belize", nom = "Bélize", nation = "portugal", case = { 327, 543 }, taille = 2, region = 1,
    produits = { "bois", "mais", "metal", "vetements", "cafe" } },
  { cle = "roatan", nom = "Roatán", nation = "portugal", case = { 380, 595 }, taille = 1, region = 1,
    produits = { "sucre", "ble", "metal", "pain", "cafe" } },
  { cle = "charleston", nom = "Charleston", nation = "france", case = { 581, 30 }, taille = 1, region = 0,
    produits = { "bois", "tissu", "briques", "viande", "teinture" } },
  { cle = "fort_caroline", nom = "Fort Caroline", nation = "france", case = { 542, 110 }, taille = 1, region = 0,
    produits = { "coton", "tissu", "briques", "viande", "teinture" } },
  { cle = "st_augustin", nom = "St-Augustin", nation = "france", case = { 540, 134 }, taille = 2, region = 0,
    produits = { "sucre", "ble", "briques", "vetements", "teinture" } },
  { cle = "grand_bahama", nom = "Grand Bahama", nation = "hollande", case = { 616, 249 }, taille = 3, region = 2,
    produits = { "fruits", "mais", "briques", "rhum", "tabac" } },
  { cle = "eleuthera", nom = "Eleuthera", nation = "hollande", case = { 668, 264 }, taille = 1, region = 2,
    produits = { "fruits", "tissu", "chanvre", "cordage", "tabac" } },
  { cle = "nassau", nom = "Nassau", nation = "hollande", case = { 647, 305 }, taille = 1, region = 2,
    produits = { "fruits", "mais", "coton", "pain", "tabac" } },
  { cle = "ile_cat", nom = "Ile Cat", nation = "hollande", case = { 706, 311 }, taille = 1, region = 2,
    produits = { "fruits", "tissu", "chanvre", "rhum", "tabac" } },
  { cle = "charles_towne", nom = "Charles Towne", nation = "hollande", case = { 744, 329 }, taille = 1, region = 2,
    produits = { "fruits", "mais", "metal", "rhum", "tabac" } },
  { cle = "nombre_de_dios", nom = "Nombre de Dios", nation = "espagne", case = { 452, 377 }, taille = 1, region = 2,
    produits = { "bois", "tissu", "chanvre", "vetements", "tabac" } },
  { cle = "evangelista", nom = "Evangelista", nation = "espagne", case = { 485, 401 }, taille = 1, region = 2,
    produits = { "fruits", "tissu", "chanvre", "cordage", "tabac" } },
  { cle = "la_havane", nom = "La Havane", nation = "espagne", case = { 500, 361 }, taille = 2, region = 2,
    produits = { "coton", "ble", "briques", "rhum", "tabac" } },
  { cle = "trinite", nom = "Trinité", nation = "espagne", case = { 588, 411 }, taille = 1, region = 2,
    produits = { "bois", "tissu", "sucre", "outils", "tabac" } },
  { cle = "andros", nom = "Andros", nation = "france", case = { 653, 327 }, taille = 1, region = 2,
    produits = { "fruits", "ble", "coton", "cordage", "tabac" } },
  { cle = "gibara", nom = "Gibara", nation = "espagne", case = { 695, 425 }, taille = 1, region = 2,
    produits = { "coton", "ble", "metal", "pain", "tabac" } },
  { cle = "santiago", nom = "Santiago", nation = "espagne", case = { 705, 466 }, taille = 1, region = 2,
    produits = { "bois", "coton", "chanvre", "outils", "tabac" } },
  { cle = "tortuga", nom = "Tortuga", nation = "angleterre", case = { 799, 471 }, taille = 1, region = 2,
    produits = { "coton", "sucre", "chanvre", "rhum", "tabac" } },
  { cle = "port_au_prince", nom = "Port-au-Prince", nation = "angleterre", case = { 782, 515 }, taille = 1, region = 2,
    produits = { "sucre", "tissu", "briques", "outils", "tabac" } },
  { cle = "iles_turques", nom = "Iles Turques", nation = "angleterre", case = { 811, 411 }, taille = 3, region = 2,
    produits = { "coton", "sucre", "chanvre", "vetements", "tabac" } },
  { cle = "isabela", nom = "Isabela", nation = "angleterre", case = { 842, 474 }, taille = 1, region = 2,
    produits = { "bois", "tissu", "chanvre", "cordage", "tabac" } },
  { cle = "saint_domingue", nom = "Saint-Domingue", nation = "angleterre", case = { 894, 526 }, taille = 1, region = 2,
    produits = { "sucre", "tissu", "briques", "pain", "tabac" } },
  { cle = "san_juan", nom = "San Juan", nation = "angleterre", case = { 1017, 516 }, taille = 2, region = 2,
    produits = { "fruits", "tissu", "chanvre", "rhum", "tabac" } },
  { cle = "saint_thome", nom = "Saint-Thome", nation = "angleterre", case = { 1032, 514 }, taille = 1, region = 2,
    produits = { "fruits", "mais", "coton", "rhum", "tabac" } },
  { cle = "saint_martin", nom = "Saint-Martin", nation = "angleterre", case = { 1082, 513 }, taille = 1, region = 3,
    produits = { "fruits", "mais", "briques", "rhum", "cacao" } },
  { cle = "saint_christophe", nom = "Saint-Christophe", nation = "angleterre", case = { 1117, 547 }, taille = 1, region = 3,
    produits = { "fruits", "mais", "metal", "rhum", "cacao" } },
  { cle = "antigua", nom = "Antigua", nation = "angleterre", case = { 1134, 558 }, taille = 1, region = 3,
    produits = { "fruits", "tissu", "briques", "cordage", "cacao" } },
  { cle = "guadeloupe", nom = "Guadeloupe", nation = "angleterre", case = { 1136, 587 }, taille = 2, region = 3,
    produits = { "fruits", "mais", "briques", "pain", "cacao" } },
  { cle = "granada", nom = "Granada", nation = "angleterre", case = { 1144, 714 }, taille = 1, region = 3,
    produits = { "fruits", "mais", "chanvre", "cordage", "cacao" } },
  { cle = "sainte_lucie", nom = "Sainte-Lucie", nation = "angleterre", case = { 1163, 677 }, taille = 1, region = 3,
    produits = { "coton", "mais", "metal", "cordage", "cacao" } },
  { cle = "martinique", nom = "Martinique", nation = "angleterre", case = { 1177, 655 }, taille = 1, region = 3,
    produits = { "fruits", "ble", "chanvre", "outils", "cacao" } },
  { cle = "la_barbade", nom = "La Barbade", nation = "angleterre", case = { 1207, 666 }, taille = 1, region = 3,
    produits = { "fruits", "tissu", "metal", "cordage", "cacao" } },
  { cle = "providence", nom = "Providence", nation = "portugal", case = { 542, 742 }, taille = 1, region = 1,
    produits = { "coton", "tissu", "metal", "cordage", "cafe" } },
  { cle = "iles_caimans", nom = "Iles Caïmans", nation = "espagne", case = { 507, 484 }, taille = 1, region = 2,
    produits = { "fruits", "sucre", "chanvre", "outils", "tabac" } },
  { cle = "port_royale", nom = "Port Royale", nation = "espagne", case = { 668, 548 }, taille = 3, region = 2,
    produits = { "coton", "mais", "metal", "rhum", "tabac" } },
  { cle = "carthagene", nom = "Carthagène", nation = "espagne", case = { 721, 802 }, taille = 2, region = 1,
    produits = { "bois", "sucre", "metal", "viande", "cafe" } },
  { cle = "santa_marta", nom = "Santa Marta", nation = "espagne", case = { 761, 760 }, taille = 1, region = 1,
    produits = { "sucre", "mais", "chanvre", "viande", "cafe" } },
  { cle = "maracaibo", nom = "Maracaïbo", nation = "espagne", case = { 830, 781 }, taille = 1, region = 1,
    produits = { "bois", "coton", "sucre", "viande", "cafe" } },
  { cle = "gibraltar", nom = "Gibraltar", nation = "espagne", case = { 844, 844 }, taille = 1, region = 1,
    produits = { "bois", "ble", "chanvre", "vetements", "cafe" } },
  { cle = "coro", nom = "Coro", nation = "espagne", case = { 903, 749 }, taille = 1, region = 3,
    produits = { "coton", "ble", "briques", "vetements", "cacao" } },
  { cle = "curacao", nom = "Curaçao", nation = "espagne", case = { 929, 747 }, taille = 1, region = 3,
    produits = { "bois", "mais", "briques", "viande", "cacao" } },
  { cle = "puerto_cabello", nom = "Puerto Cabello", nation = "espagne", case = { 949, 777 }, taille = 1, region = 3,
    produits = { "coton", "ble", "metal", "cordage", "cacao" } },
  { cle = "caracas", nom = "Caracas", nation = "espagne", case = { 984, 774 }, taille = 1, region = 3,
    produits = { "sucre", "ble", "briques", "outils", "cacao" } },
  { cle = "margarita", nom = "Margarita", nation = "espagne", case = { 1088, 754 }, taille = 2, region = 3,
    produits = { "bois", "ble", "chanvre", "pain", "cacao" } },
  { cle = "puerto_santo", nom = "Puerto Santo", nation = "espagne", case = { 1132, 767 }, taille = 1, region = 3,
    produits = { "bois", "tissu", "chanvre", "vetements", "cacao" } },
  { cle = "port_d_espagne", nom = "Port-d'Espagne", nation = "espagne", case = { 1163, 761 }, taille = 1, region = 3,
    produits = { "sucre", "ble", "chanvre", "outils", "cacao" } },
  { cle = "georgeville", nom = "Georgeville", nation = "espagne", case = { 1219, 838 }, taille = 1, region = 3,
    produits = { "bois", "ble", "briques", "outils", "cacao" } },
}
