-- Les retouches de placement faites à la main, dans l'éditeur de villes (F2).
--
-- Ce fichier est SÉPARÉ de `sim/villes_pr3.lua` exprès. Celui-là est extrait des
-- archives de Port Royale 3 et se régénère d'un coup ; écrire dedans, c'est
-- perdre son travail à la prochaine extraction. Ici, rien n'est généré : on ne
-- garde que les villes dont on a bougé quelque chose, et l'archipel applique ces
-- retouches par-dessus les données du jeu.
--
--   case      le mouillage, en cases du masque — le point RÉEL du port, celui
--             où le navire s'arrête et où le clic tombe.
--   decalage  ne bouge QUE l'image du village, en unités de monde.
--
-- Réécrit intégralement par l'éditeur : ce qui n'est pas dans la table a repris
-- sa place d'origine.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- VIDÉ, ET C'EST MESURÉ. Ce fichier a porté les SOIXANTE villes, déplacées à la
-- main à l'époque où le décor était une illustration étrangère, dont la
-- géographie n'est pas celle de Port Royale 3. Rapportées au masque de
-- navigation du jeu, ces retouches donnaient :
--
--     retouches : 18 ports EN PLEINE TERRE, 36 à quatre cases ou plus du
--                 rivage dont 26 au-delà de dix — distance moyenne 10,57 cases
--     cases PR3 : AUCUN sur la terre, 54 à une case du rivage, 6 à deux,
--                 aucun au-delà — distance moyenne 1,10 case
--
-- Un mouillage, chez PR3, est une case de MER bordant la terre. Les siennes le
-- sont toutes ; les retouches ne l'étaient qu'une fois sur soixante. On rend
-- donc la main aux données du jeu.
--
-- Les `decalage` partent avec : ils ne bougent que l'image du village, mais ils
-- ont été réglés contre la même géographie étrangère — jusqu'à 157 unités pour
-- Carthagène — et ne veulent plus rien dire une fois le mouillage à sa place.
--
-- Pourquoi personne ne pouvait les annuler : `Bridge.source_reglages` jugeait
-- qu'une ville « a bougé » en la comparant à `Origines`, une table bâtie sur
-- `Archipel.ports` — donc sur les positions DÉJÀ retouchées. Chaque ville était
-- comparée à elle-même, aucun déplacement n'était jamais vu, et l'éditeur
-- réécrivait indéfiniment ce qu'il aurait dû oublier. Corrigé : la référence se
-- lit maintenant sur `caseOrigine`, posé par `sim/archipel.lua`.
-- ─────────────────────────────────────────────────────────────────────────────

return {
}
